name: Run Tests

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose the Python version you need
        
      - name: install pip
        run: python3 get-pip.py

      - name: install pytest
        run: pip3 install -U pytest

      - name: Run Tests
        run: pytest main.py  # Replace with the appropriate command to run your tests
