name: Run Tests

on:
  push:
    branches:
<<<<<<< HEAD
      - main # Change this to the branch you want to trigger on
=======
      - main  # Change this to the branch you want to trigger on
>>>>>>> origin/main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose the Python version you need

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Replace with your package manager and dependencies

      - name: Run Tests
        run: pytest main.py  # Replace with the appropriate command to run your tests
